modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      enable_http2: true
      valid_status_codes: []  # Defaults to 2xx
      preferred_ip_protocol: ip4
      ip_protocol_fallback: true
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
  http_404_or_403:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      enable_http2: true
      valid_status_codes: [404, 403]  # Expecting 404 as a valid response
      preferred_ip_protocol: ip4
      ip_protocol_fallback: true
      fail_if_ssl: false
      tls_config:
        insecure_skip_verify: false
  tcp_connect:
    prober: tcp
    timeout: 5s
  icmp:
    prober: icmp
    timeout: 5s
