version: "3.3"

services:
  mysql:
    container_name: mysql
    image: elestio/mysql:8.0
    restart: always
    hostname: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "172.17.0.1:50778:3306"

  glpi:
    container_name: glpi
    image: glpi_custom:10.15
    restart: always
    hostname: glpi
    ports:
      - "172.17.0.1:80:80"
      - "172.17.0.1:443:443"
      - "172.17.0.1:465:465"
      - "172.17.0.1:587:587"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage/var/www/html/glpi/:/var/www/html/glpi
      - ./php/apache/php.ini:/etc/php/8.1/apache2/php.ini
      - ./php/mods-available/opcache.ini:/etc/php/8.1/mods-available/opcache.ini
    environment:
      - TIMEZONE=Asia/Karachi

#  pma:
#    image: phpmyadmin
#    restart: always
#    links:
#      - mysql:mysql
#    ports:
#      - "172.17.0.1:22811:80"
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: ${ADMIN_PASSWORD}
#      UPLOAD_LIMIT: 500M
#      MYSQL_USERNAME: glpi
#      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
#    depends_on:
#      - mysql
